import math
print(math.ceil(5.67))
print(math.ceil(-45.34)-math.ceil(6))
print(math.floor(5.67))
print(math.floor(22))
print(math.floor(-4.78))
print(math.factorial(6))
print(math.factorial(1))
print(math.factorial(0))
print(math.gcd(1024, 144))
print(math.fabs(-15))
print(math.exp(3))
print(math.log(12))
print(math.log10(25))
print(math.log(6, 4))
print(math.pow(5, 6))
print(math.pi+6)
print(math.cos(3))
print(math.sin(2*math.pi))

